// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bxyqotitejosftfpplzp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ4eXFvdGl0ZWpvc2Z0ZnBwbHpwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQwNTU1NjIsImV4cCI6MjA2OTYzMTU2Mn0.ng9m8UOb7iw8FtMs2ZqlLX4IioFKSZ5oc9epxSSHQpQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});